<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
/**
 * Fellesdata Suspicious Integration - Index
 *
 * @package         local/fellesdata
 * @subpackage      suspicious
 * @copyright       2014        eFaktor {@link http://www.efaktor.no}
 * @license         http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 * @creationDate    29/12/2016
 * @author          eFaktor     (fbv)
 *
 */
require_once($CFG->dirroot.'/lib/formslib.php');

class suspicious_form extends moodleform {
    function definition (){
        // Form
        $form               = $this->_form;

        list($from,$to) = $this->_customdata;

        $form->addElement('header', 'header_filter', get_string('filter'));
        $form->setExpanded('header_filter',true);
        
        // Date selector - From
        $form->addElement('date_selector','date_from',get_string('from','local_fellesdata'));
        $form->setDefault('date_from', $from);
        // Date selector - To
        $form->addElement('date_selector','date_to',get_string('to','local_fellesdata'));
        $form->setDefault('date_to', $to);
        
        $this->add_action_buttons(false, get_string('search'));
    }//definition

    function validation($data, $files) {
        // local time
        $time = time();
        
        $errors = parent::validation($data, $files); // TODO: Change the autogenerated stub
        
        if ($data['date_from'] > $time) {
            $errors['date_from'] = get_string('big_date','local_fellesdata');
        }else if ($data['date_from'] > $data['date_to']) {
            $errors['date_from'] = get_string('from_to','local_fellesdata');
        }else if ($data['date_to'] > $time) {
            $errors['date_to'] = get_string('big_date','local_fellesdata');
        }

        return $errors;
    }
}//suspicious_form