<?php
/**
 * Fellesdata Suspicious Integration - Index
 *
 * @package         local/fellesdata
 * @subpackage      suspicious
 * @copyright       2014        eFaktor {@link http://www.efaktor.no}
 *
 * @creationDate    29/12/2016
 * @author          eFaktor     (fbv)
 *
 */
require_once($CFG->dirroot.'/lib/formslib.php');

class suspicious_form extends moodleform {
    function definition (){
        // Form
        $form               = $this->_form;

        $form->addElement('header', 'header_filter', get_string('filter'));
        $form->setExpanded('header_filter',true);
        
        // Date selector - From
        $form->addElement('date_selector','date_from',get_string('from','local_fellesdata'));
        $form->setDefault('date_from', 0);
        // Date selector - To
        $form->addElement('date_selector','date_to',get_string('to','local_fellesdata'));
        $form->setDefault('date_to', 0);
        
        $this->add_action_buttons(false, get_string('search'));
    }//definition

    function validation($data, $files) {
        // local time
        $time = time();
        
        $errors = parent::validation($data, $files); // TODO: Change the autogenerated stub
        
        if ($data['date_from'] > $time) {
            $errors['date_from'] = get_string('big_date','local_fellesdata');
        }else if ($data['date_from'] > $data['date_to']) {
            $errors['date_from'] = get_string('from_to','local_fellesdata');
        }else if ($data['date_to'] > $time) {
            $errors['date_to'] = get_string('big_date','local_fellesdata');
        }

        return $errors;
    }
}//suspicious_form